CREATE TABLE IF NOT EXISTS el_articles (
  wp_id BIGINT UNSIGNED NOT NULL,
  slug VARCHAR(255) NOT NULL,
  title VARCHAR(500) NOT NULL,
  excerpt TEXT NULL,
  body LONGTEXT NULL,
  date DATETIME NOT NULL,
  modified DATETIME NULL,
  author VARCHAR(250) NOT NULL DEFAULT 'ElectronLibre',
  author_slug VARCHAR(120) NULL,
  author_user_id BIGINT UNSIGNED NULL,
  categories JSON NULL,
  category_names JSON NULL,
  tags JSON NULL,
  ia_keywords JSON NULL,
  access ENUM('granted','subscribers') NOT NULL DEFAULT 'subscribers',
  lang VARCHAR(8) NOT NULL DEFAULT 'fr',
  draft TINYINT(1) NOT NULL DEFAULT 0,
  translation_fr BIGINT UNSIGNED NULL,
  translation_en BIGINT UNSIGNED NULL,
  source_url VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (wp_id),
  KEY idx_draft_lang_date (draft, lang, date),
  KEY idx_author_user (author_user_id),
  KEY idx_slug (slug(191)),
  KEY idx_list_modified (modified, wp_id),
  KEY idx_list_draft_modified (draft, modified, wp_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
